name: Publish NPM on merge
'on':
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with: 
          node-version: '15.4.0'
      - uses: pascalgn/npm-publish-action@1.3.6
        with:
          tag_name: "v%s"
          tag_message: "v%s"
          publish_command: "npm"
          publish_args: "--access public"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: 292a906c-0d7d-49f7-ad20-fafb67fd219d